### ISSUE TITLE
There is NO "create shirt" in my version of this unity project

### ISSUE THREAD

**Issue by cat3818** [developer9998/GorillaShirtsUnityProject#1]
"my version" as in the version I have but may you please fix this

**Comment by developer9998** [comment]
You likely didn't open the project right, or you have script errors.
For the former of which, use the "Add" or "Open" button in Unity Hub, the wording is based on the version you are currently using:
![image](https://github.com/user-attachments/assets/b1fc5360-59bd-4850-ba06-be44bb7dfd5e)
